package com.singularity.todo.core.database

import androidx.room3.RoomDatabaseConstructor

/**
 * Room 3 KMP constructor for [AppDatabase].
 * The actual implementation is generated by the Room KSP compiler.
 */
expect object AppDatabaseCtor : RoomDatabaseConstructor<AppDatabase>
