package com.singularity.todo.core.database

import androidx.room3.migration.Migration
import androidx.room3.util.foreignKeyCheck
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.execSQL

/**
 * Migration from v31 to v32 — drops `ai_proposal.task_id` (after backfilling it
 * into `target_id`) and rebuilds `notes` to add the
 * `task_id → tasks(id) ON DELETE SET NULL` foreign key.
 *
 * ## Why this is a MANUAL migration instead of `@DeleteColumn` + AutoMigrationSpec
 *
 * The KSP-generated variant (`AppDatabase_AutoMigration_31_32_Impl`) rebuilt the
 * tables first and then invoked `AutoMigrationSpec.onPostMigrate` — i.e. the
 * backfill `UPDATE ai_proposal SET target_id = task_id …` ran AFTER `task_id`
 * had been dropped, failing with `no such column: task_id` and rolling the whole
 * upgrade back. Every pre-v32 database was therefore stuck (found on
 * 2026-10-04 while wiring `McpServerEndToEndTest`). room3's `AutoMigrationSpec`
 * exposes only `onPostMigrate` (no `onPreMigrate`), so the backfill cannot be
 * ordered before the rebuild that way — [Migration30To31]'s KDoc documents the
 * same pitfall. The fix: own the whole `migrate()` and prepend the backfill.
 *
 * ## Targetless rows
 *
 * v32 makes `target_id` NOT NULL. A row that has neither `target_id` nor a
 * `task_id` to backfill from cannot be represented at v32 —
 * [com.singularity.todo.feature.proposals.data.ProposalMapper] already rejects
 * `targetId == null` — so it is deleted together with its
 * `ai_proposal_item` children (ON DELETE CASCADE).
 *
 * ## SQL provenance
 *
 * Steps 2–3 are the verbatim sequence previously generated by Room KSP for the
 * `AutoMigration(from = 31, to = 32)` entry (kept out of [AppDatabase] now).
 */
class Migration31To32 : Migration(31, 32) {

    override suspend fun migrate(connection: SQLiteConnection) {
        backfillTargets(connection)
        rebuildNotes(connection)
        rebuildAiProposal(connection)
        foreignKeyCheck(connection, "notes")
    }

    /** Backfill `target_id` from `task_id`, then drop rows that have no target at all. */
    private fun backfillTargets(connection: SQLiteConnection) {
        // While `task_id` still exists on the old table.
        connection.execSQL(
            "UPDATE ai_proposal SET target_id = task_id " +
                "WHERE target_id IS NULL AND task_id IS NOT NULL",
        )
        // Rows with no target cannot satisfy `target_id NOT NULL`.
        connection.execSQL("DELETE FROM ai_proposal WHERE target_id IS NULL")
    }

    /** Rebuild `notes` to add the task_id foreign key (verbatim KSP sequence). */
    private fun rebuildNotes(connection: SQLiteConnection) {
        connection.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `_new_notes` (
                `id` TEXT NOT NULL,
                `user_id` TEXT NOT NULL,
                `title` TEXT NOT NULL,
                `body_markdown` TEXT,
                `body_html` TEXT,
                `is_folder` INTEGER NOT NULL,
                `kind` TEXT NOT NULL DEFAULT 'Plain',
                `parent_note_id` TEXT,
                `is_pinned` INTEGER NOT NULL DEFAULT 0,
                `pinned_at` INTEGER,
                `color` INTEGER,
                `sort_order` INTEGER NOT NULL DEFAULT 0,
                `word_count` INTEGER NOT NULL DEFAULT 0,
                `char_count` INTEGER NOT NULL DEFAULT 0,
                `outgoing_links` TEXT NOT NULL DEFAULT '[]',
                `task_id` TEXT,
                `created_at` INTEGER NOT NULL,
                `updated_at` INTEGER NOT NULL,
                `deleted_at` INTEGER,
                `archived_at` INTEGER,
                `server_version` INTEGER NOT NULL,
                `sync_status` TEXT NOT NULL,
                `sync_error` TEXT,
                `last_synced_at` INTEGER,
                `device_id` TEXT,
                `hlc` TEXT,
                PRIMARY KEY(`id`),
                FOREIGN KEY(`task_id`) REFERENCES `tasks`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL
            )
            """.trimIndent(),
        )
        connection.execSQL(
            """
            INSERT INTO `_new_notes` (
                `id`,`user_id`,`title`,`body_markdown`,`body_html`,`is_folder`,`kind`,
                `parent_note_id`,`is_pinned`,`pinned_at`,`color`,`sort_order`,`word_count`,
                `char_count`,`outgoing_links`,`task_id`,`created_at`,`updated_at`,
                `deleted_at`,`archived_at`,`server_version`,`sync_status`,`sync_error`,
                `last_synced_at`,`device_id`,`hlc`
            ) SELECT
                `id`,`user_id`,`title`,`body_markdown`,`body_html`,`is_folder`,`kind`,
                `parent_note_id`,`is_pinned`,`pinned_at`,`color`,`sort_order`,`word_count`,
                `char_count`,`outgoing_links`,`task_id`,`created_at`,`updated_at`,
                `deleted_at`,`archived_at`,`server_version`,`sync_status`,`sync_error`,
                `last_synced_at`,`device_id`,`hlc`
            FROM `notes`
            """.trimIndent(),
        )
        connection.execSQL("DROP TABLE `notes`")
        connection.execSQL("ALTER TABLE `_new_notes` RENAME TO `notes`")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_user_id` ON `notes` (`user_id`)")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_deleted_at` ON `notes` (`deleted_at`)")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_parent_note_id` ON `notes` (`parent_note_id`)")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_is_pinned` ON `notes` (`is_pinned`)")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_archived_at` ON `notes` (`archived_at`)")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_sort_order` ON `notes` (`sort_order`)")
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_notes_task_id` ON `notes` (`task_id`)")
    }

    /** Rebuild `ai_proposal` dropping task_id, with target_id NOT NULL (verbatim KSP sequence). */
    private fun rebuildAiProposal(connection: SQLiteConnection) {
        connection.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `_new_ai_proposal` (
                `id` TEXT NOT NULL,
                `user_id` TEXT NOT NULL,
                `source` TEXT NOT NULL,
                `status` TEXT NOT NULL,
                `target_kind` TEXT NOT NULL DEFAULT 'TASK',
                `target_id` TEXT NOT NULL,
                `created_at` INTEGER NOT NULL,
                `updated_at` INTEGER NOT NULL,
                `server_version` INTEGER NOT NULL,
                `sync_status` TEXT NOT NULL,
                `sync_error` TEXT,
                `last_synced_at` INTEGER,
                `device_id` TEXT,
                `hlc` TEXT,
                PRIMARY KEY(`id`)
            )
            """.trimIndent(),
        )
        connection.execSQL(
            """
            INSERT INTO `_new_ai_proposal` (
                `id`,`user_id`,`source`,`status`,`target_kind`,`target_id`,
                `created_at`,`updated_at`,`server_version`,`sync_status`,`sync_error`,
                `last_synced_at`,`device_id`,`hlc`
            ) SELECT
                `id`,`user_id`,`source`,`status`,`target_kind`,`target_id`,
                `created_at`,`updated_at`,`server_version`,`sync_status`,`sync_error`,
                `last_synced_at`,`device_id`,`hlc`
            FROM `ai_proposal`
            """.trimIndent(),
        )
        connection.execSQL("DROP TABLE `ai_proposal`")
        connection.execSQL("ALTER TABLE `_new_ai_proposal` RENAME TO `ai_proposal`")
        connection.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_ai_proposal_user_id_target_kind_target_id` " +
                "ON `ai_proposal` (`user_id`, `target_kind`, `target_id`)",
        )
        connection.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_proposal_user_id` ON `ai_proposal` (`user_id`)")
    }
}
