#!/usr/bin/env python3
"""
Validates Maestro flow id: selectors against the TestTags.kt catalogue.

Every id: used in a Maestro flow YAML must come from the canonical set in
TestTags.kt (static constants) or be a known dynamic expansion (e.g.
navTab("today") → nav_tab_today). An unknown id: is silently ignored by
Maestro and produces a false green — this script catches those before they
reach CI.

Usage:
    python scripts/ci/validate-maestro-selectors.py [--warn] [flows-dir]

Args:
    flows-dir   Root of Maestro flows (default: Maestro/flows)
    --warn      Exit 0 even if errors are found (advisory mode for initial rollout)

Exit codes:
    0  All selectors valid (or only warnings in --warn mode)
    1  Unknown selectors found (blocking mode)
    2  Usage / file-not-found error
"""

import yaml
import re
import sys
import os
from pathlib import Path
from typing import Set, List, Tuple


# ---------------------------------------------------------------------------
# slug() — must match the algorithm in TestTags.kt
# ---------------------------------------------------------------------------
def slug(s: str) -> str:
    """Lowercase + replace runs of non-alphanumeric with underscore; trim separators at both ends."""
    result = []
    pending_sep = False
    for ch in s.strip():
        if ch.isalnum():
            if pending_sep and result:
                result.append('_')
            result.append(ch.lower())
            pending_sep = False
        else:
            pending_sep = True
    # Strip trailing non-alphanumeric
    while result and not result[-1].isalnum():
        result.pop()
    # Strip leading non-alphanumeric
    while result and not result[0].isalnum():
        result.pop(0)
    if not result:
        return "untitled"
    return ''.join(result)


# ---------------------------------------------------------------------------
# Canonical ID set from TestTags.kt static constants (copied from TAGS.md)
# Generated by: TestTagsCatalogJvmTest — do not edit manually
# ---------------------------------------------------------------------------
STATIC_IDS: Set[str] = {
    # Auth
    "auth_continue_offline_button",
    "auth_email_input",
    "auth_error_text",
    "auth_loading",
    "auth_message_text",
    "auth_password_input",
    "auth_save_server_button",
    "auth_server_key_input",
    "auth_server_url_input",
    "auth_sign_in_button",
    "auth_toggle_mode_button",
    # Navigation
    "menu_sheet",
    "nav_menu_button",
    "top_bar_back_button",
    # Tasks
    "priority_option_high",
    "priority_option_low",
    "priority_option_medium",
    "priority_option_none",
    "priority_option_urgent",
    "recurrence_ends_never",
    "recurrence_ends_on_date",
    "recurrence_end_date_value",
    "recurrence_option_daily",
    "recurrence_option_day_of_month",
    "recurrence_option_monthly",
    "recurrence_option_none",
    "recurrence_option_specific_weekdays",
    "recurrence_option_weekly",
    "recurrence_option_yearly",
    "recurrence_option_yearly_on_date",
    "tasks_fab",
    "tasks_list",
    "task_context_menu_sheet",
    "task_editor_ai_button",
    "task_editor_due_row",
    "task_editor_estimate_row",
    "task_editor_more_menu",
    "task_editor_pin_row",
    "task_editor_priority_row",
    "task_editor_project_row",
    "task_editor_recurrence_row",
    "task_editor_save",
    "task_editor_start_date_row",
    "task_editor_tags_row",
    "task_editor_title_input",
    "time_tracking_error",
    "time_tracking_start",
    "time_tracking_stop",
    # Agenda
    "agenda_saved_views_button",
    "agenda_save_current_button",
    "agenda_tag_match_all",
    "saved_agenda_add_section_confirm",
    "saved_agenda_create_fab",
    "saved_agenda_delete_button",
    "saved_agenda_empty_title",
    "saved_agenda_list_back",
    "saved_agenda_menu_copy_to_profile",
    "saved_agenda_menu_delete",
    "saved_agenda_menu_edit",
    "saved_agenda_name_input",
    "saved_agenda_overflow_button",
    "saved_agenda_save_button",
    # Pomodoro
    "pomodoro_cycle_label",
    "pomodoro_pause_button",
    "pomodoro_phase_label",
    "pomodoro_play_button",
    "pomodoro_skip_button",
    "pomodoro_stop_button",
    "pomodoro_tasks_unsupported",
    "pomodoro_timer_label",
    # Tags
    "tags_fab",
    "tags_list",
    # Notes
    "notes_backlinks_button",
    "notes_list",
    "notes_quick_add_input",
    "note_action_delete",
    "note_action_edit",
    "note_editor_body",
    "note_editor_notification_host",
    "note_editor_save",
    "note_editor_title_input",
    "note_filter_chip_all",
    "note_filter_chip_archived",
    "note_filter_chip_pinned",
    # Search
    "search_input",
    # Projects
    "project_detail_quick_add",
    "project_editor_back",
    "project_editor_description_input",
    "project_editor_name_input",
    "project_editor_notification_host",
    "project_editor_save",
    # Settings
    "settings_action_row",
    "settings_content_agenda",
    "settings_content_calendar_sync",
    "settings_content_data",
    "settings_content_interface",
    "settings_content_notifications",
    "settings_content_sync",
    "settings_dark_theme_switch",
    "settings_font_size_slider",
    "settings_notifications_enabled_switch",
    "settings_notifications_sound_switch",
    "settings_notifications_vibration_switch",
    "settings_tab_agenda",
    "settings_tab_calendar_sync",
    "settings_tab_data",
    "settings_tab_interface",
    "settings_tab_notifications",
    "settings_tab_sync",
    "settings_value_row",
    "settings_work_schedule_saturday_switch",
    "settings_work_schedule_sunday_switch",
    # Onboarding
    "onboarding_replay_row",
    "onboarding_spotlight_card",
    "onboarding_spotlight_next",
    "onboarding_spotlight_skip",
    # Sync
    "sync_attachments_switch",
    "sync_auto_sync_switch",
    "sync_interval_row",
    "sync_now_row",
    "sync_sync_now_row",
    "sync_test_connection_row",
    # Dialog
    "dialog_confirm",
    "dialog_date_picker_cancel",
    "dialog_date_picker_clear",
    "dialog_date_picker_ok",
    "dialog_dismiss",
    "dialog_title_priority",
    # Editor Overflow
    "overflow_archive",
    "overflow_delete",
    "overflow_pin",
    "overflow_restore",
    "overflow_unpin",
    # Snackbar
    "archive_notification_host",
    "chat_notification_host",
    "projects_notification_host",
    "snackbar_action",
    "snackbar_saved",
    # Backup
    "backup_create_button",
    "backup_export_settings",
    "backup_import_settings",
    "backup_restore_button",
    "backup_top_bar_back",
    # Profile
    "profile_create_button",
    "profile_create_name_input",
    "profile_item_personal",
    "profile_item_work",
    # Calendar sync
    "calendar_sync_google_connect_button",
    "calendar_sync_google_disconnect_button",
    "calendar_sync_google_import_switch",
    "calendar_sync_google_import_window",
    "calendar_sync_google_list_error",
    "calendar_sync_google_renew_warning",
    "calendar_sync_google_sync_needs_calendar",
    "calendar_sync_google_sync_now_button",
    "calendar_sync_google_sync_outcome",
    "calendar_sync_system_enable_switch",
    "calendar_sync_system_sync_now_button",
    "calendar_sync_system_unavailable",
    # Search filters
    "search_filter_has_description_switch",
    "search_filter_pinned_switch",
}

# ---------------------------------------------------------------------------
# Dynamic ID expansions — known inputs for TestTags dynamic functions
# ---------------------------------------------------------------------------
DYNAMIC_EXPANSIONS: Set[str] = {
    # navTab("Today") etc. — bottom nav tabs
    "nav_tab_today",
    "nav_tab_inbox",
    "nav_tab_upcoming",
    "nav_tab_plans",
    "nav_tab_pomodoro",
    "nav_tab_calendar",
    # menuItem(...) — menu sheet items
    "menu_archive",
    "menu_profiles",
    "menu_profile_sync",
    "menu_settings",
    # taskItem(...) — from seed flows
    "task_item_buy_milk",
    "task_item_uniquesearchabletask2026",
    "task_item_water_the_plants",
    "task_item_return_to_today",
    "task_item_return_to_inbox",
    "task_item_task_from_inbox_tab",
    "task_item_task_from_today_tab",
    "task_item_full_task_with_all_fields",
    "task_item_renameme",
    "task_item_yesterdaytask",
    "task_item_todaytask",
    "task_item_tomorrowtask",
    "task_item_write_spec",
    "task_item_worktask",
    # taskCheckbox(...) — from seed flows
    "task_checkbox_buy_milk",
    # pomodoroTaskChip(...) — from seed flows
    "pomodoro_task_chip_buy_milk",
    # savedAgendaCard(...) — used in flows
    "saved_agenda_card_work",
    "saved_agenda_card_personal",
    "saved_agenda_card_journey_view",
    "saved_agenda_card_journey_renamed",
    # agendaSection(...) — section headers used in flows
    "agenda_section_today",
    "agenda_section_no_date",
    "agenda_section_overdue",
    "agenda_section_upcoming",
    # projectCard(...) — used in flows
    "project_card_project_alpha",
    # profileItem(...) — used in profile flows
    "profile_item_personal",
    "profile_item_work",
    # Dialog.title(...) — used in flows
    "dialog_title_priority",
    "dialog_title_discard",
    "dialog_title_delete",
    "dialog_title_delete_view",
    "dialog_title_archive",
    # Note items — desktop/seed
    "note_item_by_title_meeting_notes",
    # agendaSectionTemplate(...)
    "agenda_section_template_by_tag",
    "agenda_section_template_due_date",
    # agendaSelectorOption(...)
    "agenda_selector_option_work",
    # Calendar day cells (hard-coded expanded form)
    "calendar_day_2026_09_15",
    # genUi(...)
    "genui_whatsnew",
    # Menu item slug — "Quick Search" slug = "quick_search"
    "menu_quick_search",
    # Calendar sync provider segments
    "calendar_sync_provider_google_calendar",
    "calendar_sync_provider_system_calendar",
    # Settings tabs (settingsTab function — slug of the tab name)
    "settings_tab_backup",
    "settings_tab_account",
    "settings_tab_aiprovider",
    "settings_tab_calendar",
    "settings_tab_files",
    "settings_tab_taggroups",
    "settings_tab_tags",
    "settings_tab_workschedule",
    # Menu items (menuItem function — slug of the label)
    "menu_notes",
    "menu_search",
    "menu_ai_chat",
    "menu_statistics",
    # Task actions (taskAction function)
    "task_action_archive",
    "task_action_mark_as_completed",
    "task_action_open",
    # Calendar view mode tabs (calendarViewMode function)
    "calendar_view_mode_day",
    "calendar_view_mode_4_days",
    "calendar_view_mode_week",
    "calendar_view_mode_month",
    # Accent color swatches (accentSwatch function)
    "settings_accent_swatch_blue",
    "settings_accent_swatch_purple",
    "settings_accent_swatch_pink",
    "settings_accent_swatch_red",
    "settings_accent_swatch_orange",
    "settings_accent_swatch_yellow",
    "settings_accent_swatch_green",
    "settings_accent_swatch_teal",
    # Agenda selector options (agendaSelectorOption function)
    "agenda_selector_option_none",
}

# ---------------------------------------------------------------------------
# Allowlist: IDs that appear in flows but are NOT in TestTags.kt yet are
# intentionally used (known gaps tracked in TAGS.md missing testTags list).
# These are NOT errors — the validator warns but does not fail on them.
# ---------------------------------------------------------------------------
ALLOWLIST: Set[str] = {
    # Seeded task titles used across multiple flows (not in TestTags as function inputs)
    "task_item_купить_молоко",  # Cyrillic seeded task (tasks/07-cyrillic-title.yaml)
    # Seeded task from backup round-trip
    "task_item_backuproundtriptask",
    # Seeded note titles
    "note_item_by_title_alpha",
    "note_item_by_title_beta",
    # Seeded agenda card
    "saved_agenda_card_my_active_tasks",
    # Seeded offline task
    "task_item_offline_task",
    # Add more as discovered
}

# ---------------------------------------------------------------------------
# Template variable pattern (${VAR}) used in shared sub-flows
# ---------------------------------------------------------------------------
TEMPLATE_VAR_PATTERN = re.compile(r'\$\{[A-Z_][A-Z0-9_]*\}')


# ---------------------------------------------------------------------------
# Collect all id: values from a YAML file
# ---------------------------------------------------------------------------
def collect_ids_from_file(path: Path) -> List[Tuple[str, int, str]]:
    """Return list of (id_value, line_number, flow_file) tuples."""
    ids = []
    try:
        docs = yaml.safe_load_all(path.read_text(encoding='utf-8'))
    except Exception as e:
        print(f"::error::failed to parse {path}: {e}", file=sys.stderr)
        return []

    for doc in docs:
        if not doc:
            continue
        ids.extend(_collect_ids_recursive(doc, path))

    return ids


def _collect_ids_recursive(node, path: Path, line_base: int = 0) -> List[Tuple[str, int, str]]:
    """Walk a YAML node and extract all id: values."""
    results = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key == 'id' and isinstance(value, str):
                # Get line number from YAML parse info if available
                lc = getattr(value, '__line__', None) or 0
                results.append((value, lc, str(path)))
            elif key in ('assertVisible', 'tapOn', 'extendedWaitUntil',
                         'scrollUntilVisible', 'openLink'):
                # These keys hold sub-structures that may contain id:
                results.extend(_collect_ids_recursive(value, path))
            else:
                results.extend(_collect_ids_recursive(value, path))
    elif isinstance(node, list):
        for item in node:
            results.extend(_collect_ids_recursive(item, path))
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    warn_mode = "--warn" in sys.argv
    if warn_mode:
        sys.argv.remove("--warn")

    flows_root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("Maestro/flows")
    if not flows_root.exists():
        print(f"::error::flows directory not found: {flows_root}", file=sys.stderr)
        return 2

    all_valid_ids = STATIC_IDS | DYNAMIC_EXPANSIONS | ALLOWLIST

    errors: List[str] = []
    warnings: List[str] = []
    flows_checked = 0

    for flow_path in sorted(flows_root.rglob("*.yaml")):
        # Skip helpers — they use ${VAR} templates intentionally
        if "helpers" in flow_path.parts:
            continue
        flows_checked += 1
        for id_val, line_no, _ in collect_ids_from_file(flow_path):
            # Skip template variables — they are resolved at runtime by Maestro
            if TEMPLATE_VAR_PATTERN.match(id_val):
                continue
            if id_val not in all_valid_ids:
                location = f"{flow_path}"
                if line_no:
                    location += f":{line_no}"
                errors.append(f"  {location}: unknown id: {id_val!r}")

    # Sort errors by file for stable output
    errors.sort()

    if errors:
        print("::group::Maestro selector validation errors")
        print(f"Failed: {len(errors)} unknown selector(s) in {flows_checked} flow(s)")
        print()
        for e in errors:
            print(e)
        print("::endgroup::")
        return 1

    if warnings:
        print("::group::Maestro selector warnings")
        for w in warnings:
            print(w)
        print("::endgroup::")

    print(f"✓ All selectors valid ({flows_checked} flow(s) checked)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
