#!/usr/bin/env python3
"""check_adr_references.py — find references to ADRs that no longer exist.

Why this exists (2026-10-05): Phase 2 of the spec-governance sweep archives and
deletes ADRs. Nothing in the repo verified that a deleted ADR was not still cited,
so deletions silently broke documentation links. `check-doc-dead-refs.py` does not
cover this case: it checks *file paths* that do not exist, not dated ADR slugs that
were referenced by bare token (e.g. `2026-09-27-di-module-aggregator-narrative` in
prose, without `.md`).

This is the gate that makes ADR deletion safe. A token shaped like a dated ADR slug
that resolves to no file in docs/decisions/ (including archive/) is an error,
reported with file and line.

Known false positives, seeded into the baseline rather than hidden in code:
  - regex/prefix artifacts such as `2026-09-16-nav3-type-asymmetry-adr`
  - skill slugs that were renamed, which read exactly like ADR slugs
  - ADRs legitimately cited in a historical/superseded note

Usage:
  python3 scripts/check-adr-references.py
  python3 scripts/check-adr-references.py --update-baseline
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DECISIONS_DIR = ROOT / 'docs' / 'decisions'
PLANS_DIR = ROOT / 'docs' / 'plans'
BASELINE = ROOT / 'config' / 'docs' / 'adr-refs-baseline.txt'

# A dated ADR slug: YYYY-MM-DD-<kebab-slug>. The trailing group must contain at least
# one letter, so a bare date (2026-10-05) is not treated as a reference.
TOKEN_RE = re.compile(r'\b(\d{4}-\d{2}-\d{2}-[a-z0-9]+(?:-[a-z0-9]+)+)\b')

# Files an agent actually reads. Kept explicit so adding a doc source is a decision.
SCAN_FILES = [
    ROOT / 'AGENTS.md',
    ROOT / 'ARCHITECTURE.md',
    ROOT / 'README.md',
    ROOT / 'PROGRESS.md',
    ROOT / 'CLAUDE.md',
]
SCAN_GLOBS = [
    'docs/**/*.md',
    '.agents/skills/**/*.md',
    'openspec/**/*.md',
    'config/**/*.md',
]

# Never scan generated/derived trees: they restate other files and would double-count.
# DIGEST.md is generated by refresh-decisions-digest.py and is gitignored, so its
# citations are a copy of findings that are checked at their source.
EXCLUDE_PARTS = {'node_modules', '.git', 'build', 'target', 'archive'}
EXCLUDE_FILES = {'DIGEST.md', 'SKILLS-CATALOG.md'}


def existing_slugs() -> set[str]:
    """Every dated doc slug that exists, in docs/decisions/ and docs/plans/.

    Resolving against docs/decisions/ alone made six false positives out of ten
    findings on 2026-10-05: `docs/plans/2026-10-04-mr6-retro-gate.md` and
    `docs/plans/2026-10-03-agenda-views-test-plan.md` are real files, cited by
    path, and the gate reported their dates as dangling ADR slugs.

    The gate's job is "a reference to a dated decision document that no longer
    exists", and a dated file that is present is not that — whatever directory
    it lives in. Baseline is for genuine exceptions, not for a lookup that was
    pointed at the wrong directory.
    """
    slugs: set[str] = set()
    for directory in (DECISIONS_DIR, PLANS_DIR):
        if not directory.is_dir():
            continue
        for path in directory.rglob('*.md'):
            name = path.stem
            if re.match(r'^\d{4}-\d{2}-\d{2}-', name):
                slugs.add(name)
    return slugs


def iter_sources() -> list[pathlib.Path]:
    files: list[pathlib.Path] = [f for f in SCAN_FILES if f.is_file()]
    for pattern in SCAN_GLOBS:
        for path in ROOT.glob(pattern):
            if not path.is_file():
                continue
            if any(part in EXCLUDE_PARTS for part in path.parts):
                continue
            if path.name in EXCLUDE_FILES:
                continue
            files.append(path)
    return sorted(set(files))


def find_dangling(slugs: set[str]) -> list[str]:
    """Return 'file:token' for every dated-ADR token with no matching file.

    Deliberately not keyed by line number. A line-keyed baseline breaks the moment an
    unrelated edit shifts a line, which turns a baselined exception into a spurious
    failure — the gate then gets ignored rather than fixed. A token reference is a
    property of the sentence, not of its position.
    """
    dangling: list[str] = []
    for path in iter_sources():
        try:
            text = path.read_text()
            rel = path.relative_to(ROOT)
        except (UnicodeDecodeError, OSError):
            # Unreadable file: nothing to scan, and not a finding.
            continue
        except ValueError:
            # A scanned path outside ROOT would make relative_to raise. Report it
            # rather than swallowing it, which previously made the gate silently
            # return zero findings for any ROOT/source mismatch.
            print(f'ERROR: {path} is outside ROOT ({ROOT}); fix SCAN_FILES/SCAN_GLOBS',
                  file=sys.stderr)
            continue
        seen: set[str] = set()
        for line in text.splitlines():
            for match in TOKEN_RE.finditer(line):
                token = match.group(1)
                # Tolerate an explicit .md suffix and a docs/decisions/ prefix.
                token = token.removesuffix('.md')
                if token in slugs:
                    continue
                key = f'{rel}:{token}'
                if key not in seen:
                    seen.add(key)
                    dangling.append(key)
    return sorted(dangling)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--update-baseline', action='store_true',
                        help='rewrite the baseline from current findings, then exit')
    parser.add_argument('--baseline', default=str(BASELINE))
    args = parser.parse_args()

    slugs = existing_slugs()
    if not slugs:
        sys.exit(f'check_adr_references.py: no ADRs found under {DECISIONS_DIR}')

    dangling = find_dangling(slugs)

    if args.update_baseline:
        header = (
            '# Accepted dangling ADR references.\n'
            '#\n'
            '# Each line is <file>:<token>. A token is a dated ADR slug that no\n'
            '# longer resolves to a file in docs/decisions/ (or its archive/).\n'
            '#\n'
            '# Seeded at 2026-10-05 with the pre-existing set, so the gate starts green\n'
            '# and every future dangling reference is a hard failure. Entries here are\n'
            '# accepted debt, not permission to ignore them: each one should eventually\n'
            '# be repointed or removed.\n'
            '#\n'
            '# Regenerate deliberately: python3 scripts/check-adr-references.py --update-baseline\n'
            '\n'
        )
        pathlib.Path(args.baseline).write_text(header + '\n'.join(dangling) + ('\n' if dangling else ''))
        print(f'check_adr_references: wrote {len(dangling)} entr(ies) to {args.baseline}')
        return

    baseline_path = pathlib.Path(args.baseline)
    accepted: set[str] = set()
    if baseline_path.exists():
        accepted = {l.strip() for l in baseline_path.read_text().splitlines()
                    if l.strip() and not l.startswith('#')}

    new = [d for d in dangling if d not in accepted]
    stale = sorted(accepted - set(dangling))

    for entry in new:
        print(f'ERROR: dangling ADR reference — {entry}')

    if stale:
        print('')
        print(f'check_adr_references: {len(stale)} baseline entr(ies) no longer occur; '
              'remove them with --update-baseline')

    if new:
        print('')
        print(f'check_adr_references.py: {len(new)} dangling ADR reference(s) '
              f'({len(dangling) - len(new)} baselined)')
        print('Fix: repoint the reference at the current slug, or drop it. If it is a '
              'legitimate exception, add the exact "<file>:<token>" line to '
              f'{baseline_path.relative_to(ROOT)}.')
        sys.exit(1)

    print(f'check_adr_references.py: OK — {len(slugs)} ADR slugs, '
          f'{len(dangling) - len(stale)} baselined reference(s), 0 new')


if __name__ == '__main__':
    main()
