#!/usr/bin/env bash
# regen-skills-catalog.sh — regenerate docs/SKILLS-CATALOG.md from skill frontmatter.
#
# Why a plain file and not a "router skill": skill `description` fields all sit in
# context before any skill is chosen, so a 90-entry meta-skill would spend that budget
# re-listing what discovery already does. A plain file is referenced by pointer instead.
#
# Usage: ./scripts/regen-skills-catalog.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$ROOT/.agents/skills"
OUT="$ROOT/docs/SKILLS-CATALOG.md"

python3 - "$SKILLS_DIR" "$OUT" <<'PY'
import pathlib
import re
import sys
from datetime import date

skills_dir, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])

def parse(skill_md: pathlib.Path):
    text = skill_md.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fm = text[3:end]
    name = re.search(r"^name:\s*(.+)$", fm, re.M)
    desc = re.search(r"^description:\s*(.+)$", fm, re.M)
    if not name or not desc:
        return None
    d = desc.group(1).strip()
    if len(d) >= 2 and d[0] == d[-1] and d[0] in "\"'":
        d = d[1:-1]
    n = name.group(1).strip()
    if len(n) >= 2 and n[0] == n[-1] and n[0] in "\"'":
        n = n[1:-1]
    lines = text.count("\n", end) + 1
    return n, d, lines

entries = []
for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
    parsed = parse(skill_md)
    if parsed:
        entries.append((skill_md.parent.name, *parsed))

PROJECT = [e for e in entries if e[0].startswith("singularity-todo-")]
GENERIC = [e for e in entries if not e[0].startswith("singularity-todo-")]
RETIRED = [e for e in entries if e[0].endswith("-RETIRED") or "RETIRED" in e[1]]

def section(title, items):
    if not items:
        return ""
    out = [f"\n## {title}\n", "| Skill | Lines | Description |", "|---|---:|---|"]
    for dirname, name, desc, lines in items:
        first = desc.split(". ")[0].rstrip(".") + "." if desc else ""
        out.append(f"| `{name}` | {lines} | {first} |")
    return "\n".join(out)

doc = f"""# Skills Catalog

> Auto-generated by `scripts/regen-skills-catalog.sh`. Run `just docs-regen` after
> adding, renaming or retiring a skill — do not edit this file by hand.
>
> Rules for *writing* a skill: `writing-for-agents` skill.
> Budgets enforced by `python3 scripts/check-doc-sizes.py`: SKILL.md <= 500 lines,
> `description` <= 1024 chars.

{len(entries)} skills: {len(PROJECT)} project-specific, {len(GENERIC)} generic/meta.
The `description` field is the index — skill loaders discover skills by it, so it should
state *which tasks need the skill*, not summarise its contents.

{section("Project skills — `singularity-todo-*`", [e for e in PROJECT if e not in RETIRED])}
{section("Generic / meta skills", GENERIC)}
{section("Retired", RETIRED)}
"""

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(doc, encoding="utf-8")
print(f"regen-skills-catalog: {len(entries)} skills -> {out.relative_to(out.parent.parent)}")
PY
