package com.singularity.todo.core.version

/**
 * Android implementation: reads BuildConfig at runtime.
 *
 * BuildConfig is generated by androidApp into its own build directory.
 * shared/androidMain compiles first; at runtime the actual BuildConfig class
 * is on the classpath. We suppress the compilation warning via a string-based
 * class reference that resolves at runtime.
 */
actual fun appVersion(): AppVersion {
    val name = Class.forName("com.singularity.todo.BuildConfig")
        .getField("VERSION_NAME").get(null) as String
    val code = Class.forName("com.singularity.todo.BuildConfig")
        .getField("VERSION_CODE").getInt(null)
    return AppVersion(name, code)
}
